[tool.poetry]
name = "hary-django"
version = "0.1.0"
description = ""
authors = ["haru <godjaewook@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.11"
django = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
