# Generated by Django 5.1.1 on 2024-10-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_like_tweet_alter_like_user_alter_tweet_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='users',
            new_name='user',
        ),
    ]
